### ISSUE TITLE
Github Action not working for bitwarden.eu

### ISSUE THREAD

**Issue by kimdre** [bitwarden/sm-action#100]
This action does not seem to work with bitwarden.eu
Also setting the `base_url` to `bitwarden.eu` does not work, since identity and api are reachable via subdomains, not paths.

**Comment by Thomas-Avery** [comment]
Did you try using `identity_url` and `api_url`? 

```
- name: Step name
  uses: bitwarden/sm-action@v1
  with:
    access_token: ${{ secrets.ACCESS_TOKEN }}
    identity_url:  https://identity.bitwarden.eu
    api_url:  https://api..bitwarden.eu
    secrets: |
      SECRET_ID > ENVIRONMENT_VARIABLE_NAME
```
